version: '3.5'

services:
  postgres:
    container_name: powerstack_postgres
    image: postgres:10.4
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      DB_NAME: powerstack
      DB_USER: user
      DB_PASSWORD: pass
      POSTGRES_DB: powerstack
    command: -p 5432

  hasura:
    container_name: powerstack_hasura
    image: hasura/graphql-engine:v2.3.0.cli-migrations-v3
    ports:
      - '${HASURA_GRAPHQL_SERVER_PORT}:${HASURA_GRAPHQL_SERVER_PORT}'
    depends_on:
      - postgres
    restart: always
    environment:
      # https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_AUTH_HOOK: ${HASURA_AUTH_HOOK}
      HASURA_GRAPHQL_AUTH_HOOK_MODE: POST
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT}
      CUSTOM_REMOTE_SCHEMA_URL: ${CUSTOM_REMOTE_SCHEMA_URL}

    volumes:
      - ./migrations:/hasura-migrations #  mount hasura migrations folder
      - ./metadata:/hasura-metadata #  mount hasura metadata folder
    command:
      - graphql-engine
      - serve

volumes:
  pg-data:

networks:
  default:
    name: powerstack
