-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."accounts" add column "verified_email" boolean
--  null default 'false';
